openapi: 3.0.0
info:
  description:  REST API CRUD Garden.io
  version: 1.0.0
  title: Garden.io
paths:
  /api/v1/plants:
    get:
      summary: get all information of plants
      operationId: getPlants
      tags:
        - plant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plant'
    post:
      summary: create a new plant
      operationId: createPlant
      tags:
        - plant
      requestBody:
        description: Plants to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plant'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plant'
  /api/v1/plants/{id}:
    get:
      summary: get a plant by id
      operationId: getPlantById
      tags:
        - plant
      parameters:
        - name: id
          in: path
          description: id of the plant to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plant'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      summary: update a plant
      operationId: updatePlant
      tags:
        - plant
      parameters:
        - name: id
          in: path
          description: id of the plant to update
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: Plant to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plant'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plant'
        '404':
          description: Not Found
    delete:
      summary: delete a plant
      operationId: deletePlant
      tags:
        - plant
      parameters:
        - name: id
          in: path
          description: id of the plant to delete
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
  /api/v1/plants/research/{name}:
    get:
      summary: get a plant by name
      operationId: getPlantByName
      tags:
        - plant
      parameters:
        - name: name
          in: path
          description: name of the plant to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plant'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /api/v1/greenhouses:
    get:
      summary: get all information of greenhouses
      operationId: getGreenhouses
      tags:
        - greenhouse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/daoGreenhouse'
    post:
      summary: create a new greenhouse
      operationId: createGreenhouse
      tags:
        - greenhouse
      requestBody:
        description: Greenhouses to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dtoCreateGreenhouse'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/daoGreenhouse'
  /api/v1/greenhouses/{id}: 
    get:
      summary: get a greenhouse by id
      operationId: getGreenhouseById
      tags:
        - greenhouse
      parameters:
        - name: id
          in: path
          description: id of the greenhouse to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/daoGreenhouse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      summary: update a greenhouse
      operationId: updateGreenhouse
      tags:
        - greenhouse
      parameters:
        - name: id
          in: path
          description: id of the greenhouse to update
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: Greenhouse to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/daoGreenhouse'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/daoGreenhouse'
        '404':
          description: Not Found
    delete:
      summary: delete a greenhouse
      operationId: deleteGreenhouse
      tags:
        - greenhouse
      parameters:
        - name: id
          in: path
          description: id of the greenhouse to delete
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/daoGreenhouse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'


  /api/v1/users:
    get:
      summary: get all information of users
      operationId: getUsers
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/daoUser'
      
    post:
      summary: create a new user
      operationId: createUser
      tags:
        - user
      requestBody:
        description: Users to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/daoUser'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dtoUser'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      
  /api/v1/users/{email}:
    get:
      summary: get a user by email
      operationId: getUserByemail
      tags:
        - user
      parameters:
        - name: email
          in: path
          description: email of the user to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dtoUser'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      summary: update a user
      operationId: updateUser
      tags:
        - user
      parameters:
        - name: email
          in: path
          description: email of the user to update
          required: true
          schema:
            type: string
      requestBody:
        description: User to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/daoUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dtoUser'
        '404':
          description: Not Found
    delete:
      summary: delete a user
      operationId: deleteUser
      tags:
        - user
      parameters:
        - name: email
          in: path
          description: email of the user to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found

  /api/v1/mapgreenhouses/{email}:
    get:
      summary: get all greenhouse of a user
      operationId: getAllUsersGreenhouse
      tags:
        - greenhouse of a user
      parameters:
        - name: email
          in: path
          description: email of the user to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/greenhouseUser'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /api/v1/mapgreenhouses:
    post:
      summary: map a greenhouse to a user
      operationId: mapGreenhouse
      tags:
        - greenhouse of a user
      requestBody:
        description: Map to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/greenhouseUser'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/greenhouseUser'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  
  /api/v1/mapgreenhouses/{email}/{greenhouse_id}: 
    delete:
      summary: delete a greenhouse from a user
      operationId: deleteGreenhouseFromUser
      tags:
        - greenhouse of a user
      parameters:
        - name: email
          in: path
          description: email of the user to delete
          required: true
          schema:
            type: string
        - name: greenhouse_id
          in: query
          description: id of the greenhouse to delete
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'


  
  /api/v1/mapplants:
    post:
      summary: map a plant to a greenhouse
      operationId: mapPlant
      tags:
        - plants of a greenhouse
      requestBody:
        description: Map to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dtoMapPlant'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dtoMapPlant'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  
  /api/v1/mapplants/{greenhouse_id}:
    get:
      summary: get all plants of a greenhouse
      operationId: getAllGreenhousePlants
      tags:
        - plants of a greenhouse
      parameters:
        - name: greenhouse_id
          in: path
          description: id of the greenhouse to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dtoMapPlant'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /api/v1/mapplants/{greenhouse_id}/{plant_id}:
    put:
      summary: update a plant of a greenhouse
      operationId: updatePlantOfGreenhouse
      tags:
        - plants of a greenhouse
      parameters:
        - name: greenhouse_id
          in: path
          description: id of the greenhouse to update
          required: true
          schema:
            type: integer
            minimum: 1
        - name: plant_id
          in: query
          description: id of the plant to update
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: Plant to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dtoMapPlant'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dtoMapPlant'
        '404':
          description: Not Found


    delete:
      summary: delete a plant from a greenhouse
      operationId: deletePlantFromGreenhouse
      tags:
        - plants of a greenhouse
      parameters:
        - name: greenhouse_id
          in: path
          description: id of the greenhouse to delete
          required: true
          schema:
            type: integer
            minimum: 1
        - name: plant_id
          in: query
          description: id of the plant to delete
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

              



components:
  schemas:
  
    plant:
      type: object
      properties:
        idPianta:
          type: integer
          format: int32
        nomePianta:
          type: string
        descrizionePianta:
          type: string
    
    daoGreenhouse:
      type: object
      properties:
        greenhouse_id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string

    dtoCreateGreenhouse:
      type: object
      required:
        - email
        - name
      properties:
        email:
          type: string
        name:
          type: string
        description:
          type: string
        
    dtoMapPlant:
      type: object
      required:
        - greenhouse_id
        - plant_id
      properties:
        greenhouse_id:
          type: integer
          format: int32
        plant_id:
          type: integer
          format: int32

    daoMapPlant:
      type: object
      properties:
        greenhouse_id:
          type: integer
          format: int32
        plant_id:
          type: integer
          format: int32
        
    dtoUser:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        surname:
          type: string
        type:
          type: string

    daoUser:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        surname:
          type: string

    userJWT:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        surname:
          type: string
        token:
          type: string

    greenhouseUser:
      type: object
      properties:
        greenhouse_id:
          type: integer
          format: int32
        email:
          type: string

    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

