openapi: 3.0.0
info:
  description:  REST API CRUD Garden.io
  version: 1.0.0
  title: Garden.io
paths:
  /plants:
    get:
      summary: get all information of plants
      operationId: getPlants
      tags:
        - plant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plant'
    post:
      summary: create a new plant
      operationId: createPlant
      tags:
        - plant
      requestBody:
        description: Plants to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plant'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plant'
  /plants/{id}:
    get:
      summary: get a plant by id
      operationId: getPlantById
      tags:
        - plant
      parameters:
        - name: id
          in: path
          description: id of the plant to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plant'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
            
    put:
      summary: update a plant
      operationId: updatePlant
      tags:
        - plant
      parameters:
        - name: id
          in: path
          description: id of the plant to update
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: Plant to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plant'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plant'
        '404':
          description: Not Found
    delete:
      summary: delete a plant
      operationId: deletePlant
      tags:
        - plant
      parameters:
        - name: id
          in: path
          description: id of the plant to delete
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found




components:
  schemas:

    plant:
      type: object
      required:
        - PLANT_ID
        - name
        - description
      properties:
        idPianta:
          type: integer
          format: int32
        nomePianta:
          type: string
        descrizionePianta:
          type: string
    
    greenhouse:
      type: object
      required:
        - GREENHOUSE_ID
        - name
        - description
      properties:
        idGreenhouse:
          type: integer
          format: int32
        nomeGreenhouse:
          type: string
        descrizioneGreenhouse:
          type: string
    
    user:
      type: object
      required:
        - MAIL
        - name
        - surname
        - type
      properties:
        MAIL:
          type: integer
          format: int32
        name:
          type: string
        surname:
          type: string
        type:
          type: string
    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string